#!/bin/bash

# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.

# create www directory inside data dir if it doesn't exist
if [ ! -d $OPENSHIFT_DATA_DIR/www ]; then
    mkdir $OPENSHIFT_DATA_DIR/www
fi

# make sure /www directory doesn't exist inside the repo dir
if [ -d $OPENSHIFT_REPO_DIR/www ]; then
  rm -rf $OPENSHIFT_REPO_DIR/www
fi

# create symlink to www directory
ln -sf $OPENSHIFT_DATA_DIR/www $OPENSHIFT_REPO_DIR/

# put the installer to /www directory
cp -f $OPENSHIFT_REPO_DIR/.openshift/installer.php $OPENSHIFT_DATA_DIR/www/installer.php